-- What is the total revenue generated by male vs female customers
SELECT 
    gender,
    SUM(purchase_amount)
FROM customer_shopping_analysis
GROUP BY gender;

-- Which customer used a discount but still spent more than the average purchase amount
SELECT
    customer_id,
    purchase_amount
FROM customer_shopping_analysis
WHERE 
    discount_applied = 'Yes' AND
    purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_shopping_analysis);

-- What are the top 5 products with the highest average review rating
SELECT
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_review_rating
FROM customer_shopping_analysis
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5

-- Compare the average purchase amounts between standard and express shipping
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_net_revenue
FROM customer_shopping_analysis
WHERE shipping_type IN ('Express' , 'Standard')
GROUP BY shipping_type
ORDER BY avg_net_revenue DESC;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
SELECT
    subscription_status,
    COUNT(customer_id) AS customer_count,
    ROUND(AVG(purchase_amount), 2) AS avg_net_revenue,
    ROUND(SUM(purchase_amount), 2) AS net_revenue
FROM customer_shopping_analysis
GROUP BY subscription_status
ORDER BY avg_net_revenue, net_revenue;

-- Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    item_purchased,
    ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100 / COUNT(customer_id), 2) AS pct_of_purchases
FROM customer_shopping_analysis
GROUP BY item_purchased
ORDER BY pct_of_purchases DESC
LIMIT 5

-- Segment customers into New, Returning, and Loyal based on their number of previous purchases, and show the count of each segment
SELECT
    CASE
        WHEN previous_purchases > 10 THEN 'Loyal'
        WHEN previous_purchases >= 2 THEN 'Returning'
        ELSE 'New'
    END AS loyalty_of_customers,
    COUNT(customer_id) AS count_of_customers
FROM customer_shopping_analysis
GROUP BY loyalty_of_customers
ORDER BY count_of_customers DESC

-- What are the top 3 purchased products within each category?
WITH item_count AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS count_of_customers,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_shopping_analysis
    GROUP BY category, item_purchased
)

SELECT
    category,
    item_purchased,
    count_of_customers
FROM item_count
WHERE item_rank <= 3

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    subscription_status,
    SUM(CASE WHEN previous_purchases > 5 THEN 1 ELSE 0 END) AS count_of_customers
FROM customer_shopping_analysis
GROUP BY subscription_status

-- What is the revenue contribution of each age group
SELECT
    age_category,
    SUM(purchase_amount) AS net_revenue
FROM customer_shopping_analysis
GROUP BY age_category
ORDER BY net_revenue DESC


-- Count of Customers who has subscription
SELECT
    subscription_status,
    COUNT(customer_id) AS customer_count
FROM customer_shopping_analysis
GROUP BY subscription_status